defmodule RiddlerAdmin.Schema do
  @moduledoc """
  Module for accessing the database. This should be used in place of `Ecto.Schema`.

  This sets up config including:

    * Primary keys will be binary UXIDs (not generated by the DB)
    * Timestamps are :utc_datetime_usec
  """

  defmacro __using__(_opts) do
    quote do
      use Ecto.Schema

      import Ecto.Changeset

      @primary_key false
      @foreign_key_type Ecto.UXID

      @timestamps_opts [type: :utc_datetime_usec]
    end
  end
end
