defmodule RiddlerAdmin.Schema do
  @moduledoc """
  Module for accessing the database. This should be used in place of `Ecto.Schema`.

  This sets up config including:

    * Primary keys will be binary UXIDs (not generated by the DB)
    * Timestamps are :utc_datetime_usec
  """

  defmacro __using__(opts) do
    prefix = Keyword.get(opts, :id_prefix)
    size = Keyword.get(opts, :id_size, :small)
    quote do
      use Ecto.Schema

      import Ecto.Changeset

      @primary_key {:id, UXID, autogenerate: true, prefix: unquote(prefix), size: unquote(size)}
      @foreign_key_type UXID

      @timestamps_opts [type: :utc_datetime_usec]
    end
  end
end
